apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-3ufn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0007-tenant/tkrw-pr712-0075-0007-app/devfile-sample-3ufn@sha256:87683216fca9edeead49d7167f163c926d88bb1d31c2739dd1ae18c1136c9381
        name: my-nodejs
        resources: {}
status: {}
